export const CHECK_DATA_REQUEST = "CHECK_DATA_REQUEST"
export const CHECK_DATA_SUCCESS = "CHECK_DATA_SUCCESS"
export const CHECK_DATA_FAILED = "CHECK_DATA_FAILED"

export const CONNECTION_REQUEST = "CONNECTION_REQUEST"
export const CONNECTION_SUCCESS = "CONNECTION_SUCCESS"
export const CONNECTION_FAILED = "CONNECTION_FAILED"
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT"